food/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('food/', views.IndexClassView.as_view(), name='index'),
    path('food/<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('add', views.CreateItem.as_view(), name='create_item'),       #add
    path('update/<int:id>/', views.update_item, name= 'update_item'),  #update
    path('delete/<int:id>/', views.delete_item, name= 'delete_item'),  #delete
]

mysites/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'), 
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    
    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_prce = models.IntegerField()
    item_image = models.CharField(max_length=1000,default='https://www.google.com/search?q=placeholder+food+images&client=ubuntu&channel=fs&tbm=isch&source=iu&ictx=1&vet=1&fir=r4MyYWa6UxepTM%252CDE59x2KNdrhkvM%252C_%253Bjal7CZrCohPPcM%252CSht218MD2XkntM%252C_%253B7K26ALkHdMGaaM%252CpW-HFWw0VNMbnM%252C_%253BcAtq_o3hdy3hOM%252CPAwBzaJSiNcWRM%252C_%253Bi4LWV8nsfF3pZM%252Cvm_HY1Gpe19S-M%252C_%253BKzlEw1u98W7EKM%252C75wDOX_EasD4oM%252C_%253B59Y8go7tPpJqKM%252C0k5rhoJHXvlkdM%252C_%253BbrvVOAlrbLzfVM%252CwjWTBq_jYqmdeM%252C_%253B_f-j934pbgJPIM%252Ce1j17iealMc86M%252C_%253B-fO_excvO9BrdM%252C0RuYXFRXZuB68M%252C_%253B3gu7rag2AQnNmM%252C7RPpozL6R3FwOM%252C_%253BtWHGFraLIpPmbM%252C-EYq4YMSSYYZMM%252C_%253BFqgiTtdteGma4M%252CNhlb63xefFds-M%252C_%253B5nsC28LDwnHlEM%252CDTuB0awS6s_LNM%252C_&usg=AI4_-kS4Uy0trVJ_UU2EfRNF_SnuhXfZKQ&sa=X&ved=2ahUKEwiA8ougu_T3AhWP7XMBHSb5CT0Q9QF6BAgDEAE#imgrc=r4MyYWa6UxepTM')
    
    
    def get_absolute_url(self):
        return reverse('food:detail', kwargs={"pk": self.pk})       
    
    

users/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    
    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_prce', 'item_image']

users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from httplib2 import Http
from .models import Item
from .forms import ItemForm 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.


def index(request):
    item_list = Item.objects.all()
    context = {
        "item_list" : item_list
    }
    return  render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'
    


def detail(request, item_id):
    item = Item.objects.get(pk=item_id) 
    context ={
        'item' : item
    }
    return render(request, 'food/detail.html', context)    


class FoodDetail(DetailView):
    model = Item;
    template_name = 'food/detail.html'
    

def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form})


# This is class based view of create item
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name', 'item_desc', 'item_prce', 'item_image']
    template_name = 'food/item-form.html'
    
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        
        
        return super().form_valid(form)
        
        
def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    print(form)
    print(item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    return render(request, 'food/item-form.html', {'form': form, 'item': item})


def delete_item(request, id):
    item = Item.objects.get(id=id)
    
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    return render(request, 'food/item-delete.html', {'item':item})

users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, your account has been created successfully.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="" class="navbar-brand">Foodapp</a>

        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}">Add Item</a>
            <a class="nav-item nav-link" href="#">Delete Item</a>
            <a class="nav-item nav-link" href="#">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{% url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
        </div> 
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tag }}"> 
                 {{ message }}
            </div>
          
        {% endfor %}

    {% endif %}
    {% block body %}
    {% endblock %}
    
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img class="card" height="300px" src="{{ item.item_image }}" alt="">
            </div>

            <div class="col-md-6">
                <h1>{{ object.item_name }}</h1>
                <h1>{{ object.item_desc }}</h1>
                <h1>${{ object.item_prce }}</h1>
                <a href="{% url 'food:delete_item' item.id %}">Delete</a><br>
                <a href="{% url 'food:update_item' item.id %}">Update</a>
            </div>
        </div>
    </div>



{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

    {% block body %}

    {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{ item.item_image }}">
            </div>
            <div class="col-md-4">
                <h3> {{ item.item_name }} </h3>               
                <h5> {{ item.item_desc }} </h5>
                <h6>${{ item.item_prce}} </h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success ">Details</a>
            </div>
        </div>

    {% endfor%}
        
    {% endblock %}

food/templates/food/item-delete.html
<form action="" method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }} </h2>
    <button type="submit">Confirm</button>
</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                         {{ form }}
                        <button class="btn-info" type="submit">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.name }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button class="btn-info" type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/logout.html
<h1>You have been loggedout</h1>

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" height="200px" width="200px">

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                               <div class="form-group">
                                {{ field.name }}
                                <br>
                                {{ field }}
                               </div> 

                            {% endfor %}
                            <button  class="btn-info" type="submit">SignUp</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}